name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: amrit3533
          outputs: dist/snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Generated snake animation"
          add: "dist/snake.svg"

      - name: Upload Snake
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg
